### ISSUE TITLE
Pick up file descriptor patch?

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/reproc-feedstock#9]
### Comment:

@conda-forge/reproc How do you feel about picking up https://github.com/DaanDeMeyer/reproc/pull/103 in the feedstock to workaround the issue running mamba when the limit on the number of open file descriptors being more than 1024^2?

**Comment by chrisburr** [comment]
Ping @wolfv

**Comment by wolfv** [comment]
Yes, I would be happy about that. Should we ping @DaanDeMeyer if he wants to share maintenance of reproc?

**Comment by chaen** [comment]
Hi ! I am happy to help in either way I can ! Until we address the problem in reproc directly, can #10 be merged ? I constantly have to work around it :-)
